# Generated by Django 4.0.2 on 2022-03-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('availability', models.PositiveIntegerField()),
                ('image', models.URLField(default='https://www.google.com/search?q=not+available+images&tbm=isch&source=iu&ictx=1&vet=1&fir=vxOxwU8dc50zUM%252CVatYfpMpoyE83M%252C_%253BII52p2rCadVUPM%252C18EW1yTQh3xjuM%252C_%253Bz3RxpzX7UZ_btM%252C18EW1yTQh3xjuM%252C_%253BNpRlhznv0nm5hM%252CjvbXrKsd7yYcYM%252C_%253BqlmD0ARYYEJMkM%252Cnrzs9mxWz_fQ6M%252C_%253BQ2tH96MESObufM%252C9Gw1df-2KUwW4M%252C_%253B-5qogrM3qGFJTM%252C1UZktqelCSUecM%252C_%253B-QpL1I7u3zbiBM%252C029W-ajBtZqZzM%252C_%253BaP-kyWM8Q4PtiM%252C18EW1yTQh3xjuM%252C_%253BeHxjiJfZlQ8YIM%252ClG40uXijBDDdRM%252C_%253BBBEdEnL6NhNc6M%252C8QiAg--VP8ug1M%252C_%253BXy0uRoz83yMjtM%252C2Edn_XjmlGNSPM%252C_%253Bgxe2hOwoCz7ThM%252CEv6xIc3mXA4zNM%252C_%253Bgkt8LXP6E6efOM%252CwtuMG3bbDus38M%252C_%253BD0yF6SOHmaoxiM%252CgFBtz3eqCXuSTM%252C_%253BczXUd58IxPr9sM%252C9Gw1df-2KUwW4M%252C_&usg=AI4_-kQFTcLRh95TLP3_zRmHgjmpNgheug&sa=X&ved=2ahUKEwjTnOGx9Jf2AhXkTGwGHXv9DqQQ9QF6BAgYEAE#imgrc=-QpL1I7u3zbiBM', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNumber', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=oauth_app.models.expiry)),
                ('status', models.SmallIntegerField(choices=[(0, 'Issued'), (1, 'Returned')], default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuedbooks', to='oauth_app.book')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuedbooks', to='oauth_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='student',
            field=models.ManyToManyField(related_name='books', through='oauth_app.IssueBook', to='oauth_app.Profile'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='oauth_app.book')),
            ],
        ),
    ]
