# Generated by Django 3.2.12 on 2022-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuebook',
            options={'ordering': ('-issued_date',)},
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
