# Generated by Django 3.2.12 on 2022-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0004_auto_20220313_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxRenewtimes', models.PositiveIntegerField(default=4)),
                ('MaxRenewDays', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='RenewDays',
        ),
    ]
