# Generated by Django 3.2.12 on 2022-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0005_auto_20220313_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinePerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fine', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
