# Generated by Django 3.2.12 on 2022-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0007_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Totalfine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
