# Generated by Django 3.2.12 on 2022-03-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0009_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryaddr',
        ),
        migrations.AddField(
            model_name='book',
            name='categoryaddr',
            field=models.ManyToManyField(related_name='categories', to='oauth_app.Category'),
        ),
    ]
