# Generated by Django 3.2.12 on 2022-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0010_auto_20220330_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='students_interested',
            field=models.ManyToManyField(related_name='interest', to='oauth_app.Profile'),
        ),
    ]
