# Generated by Django 3.2.12 on 2022-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0011_book_students_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Type',
            field=models.CharField(choices=[('Book', 'Book'), ('Journal', 'Journal'), ('Thesis', 'Thesis')], default='Book', max_length=50),
        ),
    ]
