# Generated by Django 3.2.12 on 2022-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0012_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='students_interested',
            field=models.ManyToManyField(blank=True, null=True, related_name='interest', to='oauth_app.Profile'),
        ),
    ]
