# Generated by Django 3.2.12 on 2022-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0013_auto_20220401_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='NULL', max_length=50, verbose_name='ISBN/ISSN'),
        ),
    ]
