# Generated by Django 3.2.12 on 2022-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0016_auto_20220407_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='authoraddr',
            field=models.ManyToManyField(related_name='authors', to='oauth_app.Author'),
        ),
    ]
