# Generated by Django 3.2.12 on 2022-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0017_auto_20220507_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authoraddr',
            field=models.ManyToManyField(related_name='authors', to='oauth_app.Author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categoryaddr',
            field=models.ManyToManyField(related_name='categories', to='oauth_app.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='book',
            name='students_interested',
            field=models.ManyToManyField(blank=True, related_name='interest', to='oauth_app.Profile'),
        ),
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('Book', 'Book'), ('Journal', 'Journal'), ('Thesis', 'Thesis')], default='Book', max_length=50)),
                ('ISBN', models.CharField(default='NULL', max_length=50, verbose_name='ISBN/ISSN')),
                ('image', models.URLField(default='', max_length=1000)),
                ('Resourcelink', models.URLField(default='', max_length=1000)),
                ('authoraddr', models.ManyToManyField(related_name='authorsOnline', to='oauth_app.Author', verbose_name='Authors')),
                ('categoryaddr', models.ManyToManyField(related_name='categoriesOnline', to='oauth_app.Category', verbose_name='Categories')),
                ('students_interested', models.ManyToManyField(blank=True, related_name='interestOnline', to='oauth_app.Profile')),
            ],
        ),
    ]
