# Generated by Django 3.2.12 on 2022-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0018_auto_20220507_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_Faculty',
            field=models.BooleanField(default=False),
        ),
    ]
