# Generated by Django 3.2.12 on 2022-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0019_profile_is_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewday',
            name='RenewalType',
            field=models.CharField(default='Student', max_length=200),
        ),
    ]
