# Generated by Django 3.2.12 on 2022-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0021_profile_booksissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewday',
            name='BooksLimit',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
