# Generated by Django 3.2.12 on 2022-05-08 18:56

from django.db import migrations, models
import oauth_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0022_renewday_bookslimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=oauth_app.models.defaultfun),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='expiry_date',
            field=models.DateField(default=oauth_app.models.defaultfun),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issued_date',
            field=models.DateField(default=oauth_app.models.defaultfun2),
        ),
    ]
